/*
 * This file is generated by jOOQ.
*/
package com.onefactor.oauth.dao.jooq;


import com.onefactor.oauth.dao.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = com.onefactor.oauth.dao.jooq.tables.User.USER;
}
