/*
 * This file is generated by jOOQ.
*/
package com.onefactor.oauth.dao.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -766378284;

    private Long    id;
    private Long    customerId;
    private String  name;
    private String  password;
    private String  roles;
    private Boolean isEnabled;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.customerId = value.customerId;
        this.name = value.name;
        this.password = value.password;
        this.roles = value.roles;
        this.isEnabled = value.isEnabled;
    }

    public User(
        Long    id,
        Long    customerId,
        String  name,
        String  password,
        String  roles,
        Boolean isEnabled
    ) {
        this.id = id;
        this.customerId = customerId;
        this.name = name;
        this.password = password;
        this.roles = roles;
        this.isEnabled = isEnabled;
    }

    public Long getId() {
        return this.id;
    }

    public User setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getCustomerId() {
        return this.customerId;
    }

    public User setCustomerId(Long customerId) {
        this.customerId = customerId;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public User setName(String name) {
        this.name = name;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getRoles() {
        return this.roles;
    }

    public User setRoles(String roles) {
        this.roles = roles;
        return this;
    }

    public Boolean getIsEnabled() {
        return this.isEnabled;
    }

    public User setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(customerId);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(roles);
        sb.append(", ").append(isEnabled);

        sb.append(")");
        return sb.toString();
    }
}
